license = "CC0-1.0"

modLoader="javafml"
loaderVersion="[1,)"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "Tjalle"
description = "Disables Elytra flight outside The End"

logoFile = "assets/disable-elytra-flight/icon.png"

[[mixins]]
config = "disable-elytra-flight.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"
